language: python
sudo: required
# dist: trusty  # have no preinstalled riak service

services:
  - riak

before_install:
  - "sudo riak-admin bucket-type create pytest '{\"props\": {\"allow_mult\": \"False\"}}'"
  - "sudo riak-admin bucket-type activate pytest"
  - "sudo riak-admin bucket-type create pytest-counters '{\"props\": {\"datatype\": \"counter\"}}'"
  - "sudo riak-admin bucket-type activate pytest-counters"
  - "sudo riak-admin bucket-type create pytest-maps '{\"props\": {\"datatype\": \"map\"}}'"
  - "sudo riak-admin bucket-type activate pytest-maps"
  - "sudo riak-admin bucket-type create pytest-sets '{\"props\": {\"datatype\": \"set\"}}'"
  - "sudo riak-admin bucket-type activate pytest-sets"

python:
  - '3.5'

install:
  - pip install coveralls
  - python setup.py develop

script:
  - coverage run --source=aioriak setup.py test

after_success:
  - coveralls
