language: python
sudo: required
# dist: trusty  # have no preinstalled riak service

services:
  - riak

before_install:
  - export RIAK_ADMIN="riak-admin"
  - sudo python setup.py setup_riak

python:
  - '3.5.0'
  - '3.5.1'

install:
  - python setup.py develop
  - pip install coveralls

script:
  - nosetests -v

after_success:
  - coveralls
