name: py35
dependencies:
  - python=3.5.1=0
  - pip:
    - Sphinx==1.4.1
    - sphinx-autobuild==0.6.0
    - sphinx-rtd-theme==0.1.9
    - sphinxcontrib-asyncio==0.2.0
    - python3-riak-pb==2.1.0.6
    - riak==2.3.0
